### ISSUE TITLE
runtime warning when running country_specific.py in the biogenic refinery branch

### ISSUE THREAD

**Issue by lane-to** [QSD-Group/EXPOsan#2]
see attached screenshots
<img width="633" alt="Screen Shot 2022-01-31 at 5 10 58 PM" src="https://user-images.githubusercontent.com/91288288/151888380-2fcac06d-caf6-4fe3-bc7f-f9dd011652dc.png">
<img width="635" alt="Screen Shot 2022-01-31 at 5 11 42 PM" src="https://user-images.githubusercontent.com/91288288/151888385-5080ceda-6206-4835-8043-a798f0617395.png">
<img width="644" alt="Screen Shot 2022-01-31 at 5 12 15 PM" src="https://user-images.githubusercontent.com/91288288/151888390-7fd6ca58-245a-424b-b83d-fa171d271b97.png">

**Comment by yalinli2** [comment]
Thanks @lane-to for the post!

The culprit is repeat importing, specially this line:
```python
from systems import price_dct
```

When doing this, Python runs systems.py (in order to import `price_dct`), but later, you also have:
```python
systems = br.systems
sys_dct = systems.sys_dct
price_dct = systems.price_dct
GWP_dct = systems.GWP_dct
GWP = systems.GWP
```

And Python needs to run systems.py again, thus all the objects are recreated.

Taking out that `from systems import price_dct` line should let all the warnings go away, but you also have a lot of other imported but not used modules/objects (Spyder flags them with the yellow triangle with an exclamation mark inside)

<img width="837" alt="image" src="https://user-images.githubusercontent.com/49011373/152684864-1b9f6cbb-818e-4c06-a18a-1178953682f6.png">

You can take out all the modules that Spyder flags, so (with minor modifications to consolidate the codes)
```python
import models as m, systems
import pandas as pd
from chaospy import distributions as shape
import biosteam as bst
from biosteam.evaluation import Model
from qsdsan.utils import load_data, data_path
from qsdsan import ImpactItem

sys_dct = systems.sys_dct
price_dct = systems.price_dct
GWP_dct = systems.GWP_dct
GWP = systems.GWP
```

In fact, because you've pulled in some of the new changes in QSDsan, you actually do:
```python
import models as m, systems
import pandas as pd
from chaospy import distributions as shape
from qsdsan.utils import load_data, data_path
from qsdsan import ImpactItem, PowerUtility, Model

sys_dct = systems.sys_dct
price_dct = systems.price_dct
GWP_dct = systems.GWP_dct
GWP = systems.GWP
```

The first line of `import models as m, systems` is equivalent to:
```python
import models as m
import systems
```

Hope this helps, feel free to close this issue if this solves your problem, or let me know if you run into further problems!

**Comment by yalinli2** [comment]
Closing it since it's fixed
